"""update recipe creation

Revision ID: d66905358731
Revises: 
Create Date: 2023-03-29 18:46:08.415010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66905358731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_cook_temp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipe_prep_time', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipe_cook_time', sa.Integer(), nullable=False))
        batch_op.drop_column('recipe_preptime')
        batch_op.drop_column('recipe_cooktime')
        batch_op.drop_column('recipe_cooktemp')
        batch_op.drop_column('recipe_ingredients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_ingredients', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('recipe_cooktemp', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('recipe_cooktime', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('recipe_preptime', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('recipe_cook_time')
        batch_op.drop_column('recipe_prep_time')
        batch_op.drop_column('recipe_cook_temp')

    # ### end Alembic commands ###
